sudo: false
language: go
env:
  - GO111MODULE=on
go:
  - 1.11.x

# Only clone the most recent commit.
git:
  depth: 1

install: true

# Don't email me the results of the test runs.
notifications:
  email: false
